acc2:
  _target_: metrics.Accuracy
  name: acc
  format: simpleqa_like
  exclude_not_attempted: false

acc:
  _target_: metrics.Accuracy
  name: acc
  format: simpleqa_like
  exclude_not_attempted: true

ece2:
  _target_: metrics.ECE
  name: ece
  n_bins: 15
  format: simpleqa_like
  exclude_not_attempted: false

ece:
  _target_: metrics.ECE
  name: ece
  n_bins: 15
  format: simpleqa_like
  exclude_not_attempted: true

auroc2:
  _target_: metrics.AUROC
  name: auroc
  format: simpleqa_like
  exclude_not_attempted: false

auroc:
  _target_: metrics.AUROC
  name: auroc
  format: simpleqa_like
  exclude_not_attempted: true

attempted_count:
  _target_: metrics.AttemptedCount
  name: attempted_count
  format: simpleqa_like
  exclude_not_attempted: true
