name: meta-llama/Meta-Llama-3.1-8B-Instruct
base_model_id: meta-llama/Meta-Llama-3.1-8B-Instruct
save_path: null
lora_weight_path: null
temperature: 0.7
top_p: 0.95
top_k: 50
min_p: 0.0
max_tokens: 4096