defaults:
  - grader_model: meta-llama/llama-3.1-8b-instruct

name: simple_qa
url: https://huggingface.co/datasets/basicv8vc/SimpleQA/blob/main/simple_qa_test_set.csv
file_path: llm_linguistic_confidence_study/datasets/simple_qa_test_set.csv
